import { useEffect, useState } from 'react';
import { useProviderModels } from '../hooks/useProviderModels';
import { useProviderVoices } from '../hooks/useProviderVoices';
import { useCodexLogin, useProviders } from '../hooks/useProviders';
import AssetUpload from './AssetUpload';
const STYLES = [{ value: 'product', label: 'Product teaser' }, { value: 'explainer', label: 'Explainer' }, { value: 'social', label: 'Social clip' }];
const VOICE_PROVIDERS = { 'openai-tts': 'OpenAI TTS', 'minimax-tts': 'MiniMax TTS', 'google-cloud-tts': 'Google Cloud TTS', 'cartesia-tts': 'Cartesia' };
const VOICES = {
  'openai-tts': [{ value: 'alloy', label: 'Alloy · balanced' }, { value: 'ash', label: 'Ash' }, { value: 'ballad', label: 'Ballad' }, { value: 'coral', label: 'Coral · warm' }, { value: 'echo', label: 'Echo' }, { value: 'fable', label: 'Fable' }, { value: 'nova', label: 'Nova' }, { value: 'onyx', label: 'Onyx' }, { value: 'sage', label: 'Sage' }, { value: 'shimmer', label: 'Shimmer' }, { value: 'verse', label: 'Verse' }, { value: 'marin', label: 'Marin · recommended' }, { value: 'cedar', label: 'Cedar · recommended' }],
  'minimax-tts': [{ value: 'English_expressive_narrator', label: 'Expressive narrator' }, { value: 'English_CalmLady', label: 'Calm lady' }, { value: 'English_Trustworth_Man', label: 'Trustworthy man' }],
  'google-cloud-tts': [{ value: 'en-US-Neural2-F', label: 'Neural F · warm' }, { value: 'en-US-Neural2-D', label: 'Neural D · steady' }, { value: 'en-US-Neural2-C', label: 'Neural C · bright' }]
};
const LS_KEY = 'aiugc-maker-form-v1'; const CONFIG_KEY = 'aiugc-maker-config-v1';
function loadDraft() { try { const d = JSON.parse(localStorage.getItem(LS_KEY)); return d && typeof d === 'object' ? d : null; } catch { return null; } }
function loadConfig() { try { const d = JSON.parse(localStorage.getItem(CONFIG_KEY)); return d && typeof d === 'object' ? d : null; } catch { return null; } }
export default function PromptForm({ onSubmit, loading }) {
  const [brief, setBrief] = useState(''), [durationSec, setDurationSec] = useState(15), [style, setStyle] = useState('product'), [music, setMusic] = useState(false), [voiceover, setVoiceover] = useState(false), [voiceoverProvider, setVoiceoverProvider] = useState('openai-tts'), [voiceoverVoice, setVoiceoverVoice] = useState('coral'), [customVoiceId, setCustomVoiceId] = useState(false), [voiceoverOffsetSec, setVoiceoverOffsetSec] = useState(0), [durationMode, setDurationMode] = useState('fixed'), [composer, setComposer] = useState('template'), [provider, setProvider] = useState('openai-codex'), [model, setModel] = useState(''), [assets, setAssets] = useState([]), [connectError, setConnectError] = useState(''), [hydrated, setHydrated] = useState(false);
  const { providers, refresh: refreshProviders } = useProviders(); const selectedProvider = providers.find(p => p.id === provider); const { models, loading: modelsLoading, error: modelsError, refresh: refreshModels } = useProviderModels(provider); const { login, connect, cancel } = useCodexLogin(async () => { await refreshProviders(); await refreshModels(); });
  const { voices: cartesiaVoices, loading: cartesiaVoicesLoading, error: cartesiaVoicesError } = useProviderVoices(voiceoverProvider === 'cartesia-tts' ? 'cartesia-tts' : null);
  const voiceOptions = voiceoverProvider === 'cartesia-tts' ? cartesiaVoices.map(v => ({ value: v.id, label: v.name + (v.gender ? ` · ${v.gender}` : '') })) : (VOICES[voiceoverProvider] || VOICES['openai-tts']);
  useEffect(() => { const d = loadDraft(), c = loadConfig(); const settings = c || d; if (settings) { if (settings.durationSec) setDurationSec(settings.durationSec); if (settings.style) setStyle(settings.style); if (typeof settings.music === 'boolean') setMusic(settings.music); if (typeof settings.voiceover === 'boolean') setVoiceover(settings.voiceover); if (settings.voiceoverProvider) setVoiceoverProvider(settings.voiceoverProvider); if (settings.voiceoverVoice) setVoiceoverVoice(settings.voiceoverVoice); if (typeof settings.customVoiceId === 'boolean') setCustomVoiceId(settings.customVoiceId); if (typeof settings.voiceoverOffsetSec === 'number') setVoiceoverOffsetSec(settings.voiceoverOffsetSec); if (settings.durationMode === 'voiceover') setDurationMode('voiceover'); if (settings.composer) setComposer(settings.composer); if (settings.provider) setProvider(settings.provider); if (settings.model) setModel(settings.model); } if (d) { if (d.brief) setBrief(d.brief); if (Array.isArray(d.assets)) setAssets(d.assets); } setHydrated(true); }, []);
  useEffect(() => { if (hydrated) { localStorage.setItem(CONFIG_KEY, JSON.stringify({ durationSec, style, music, voiceover, voiceoverProvider, voiceoverVoice, customVoiceId, voiceoverOffsetSec, durationMode, composer, provider, model })); localStorage.setItem(LS_KEY, JSON.stringify({ brief, assets })); } }, [hydrated, brief, durationSec, style, music, voiceover, voiceoverProvider, voiceoverVoice, customVoiceId, voiceoverOffsetSec, durationMode, composer, provider, model, assets]);
  useEffect(() => { if (!voiceover && durationMode === 'voiceover') setDurationMode('fixed'); }, [voiceover]);
  useEffect(() => { if (models.length && !models.some(m => m.id === model)) setModel(models.find(m => m.default)?.id || models[0].id); }, [models]);
  useEffect(() => { if (!customVoiceId && voiceOptions.length && !voiceOptions.some(v => v.value === voiceoverVoice)) setVoiceoverVoice(voiceOptions[0].value); }, [voiceOptions, customVoiceId]);
  const connectCodex = async flow => { setConnectError(''); try { const result = await connect(flow); if (result.authUrl) window.open(result.authUrl, '_blank', 'noopener,noreferrer'); } catch (e) { setConnectError(e.message); } };
  const updateAssets = updater => setAssets(prev => typeof updater === 'function' ? updater(prev) : updater);
  const submit = e => { e.preventDefault(); if (!brief.trim() || (composer === 'agent' && !model) || (voiceover && !voiceoverVoice.trim())) return; onSubmit({ brief: brief.trim(), durationSec, style, music, voiceover, voiceoverProvider, voiceoverVoice, voiceoverOffsetSec: voiceover ? voiceoverOffsetSec : 0, durationMode: voiceover ? durationMode : 'fixed', composer, provider: composer === 'agent' ? provider : undefined, model: composer === 'agent' ? model : undefined, assets: assets.length ? assets : undefined }); setBrief(''); };
  const codexConnected = selectedProvider?.authState === 'connected';
  return <form onSubmit={submit}>
    <div className="panel"><div className="eyebrow">New generation</div><h2>What should we make?</h2><textarea className="brief" value={brief} onChange={e => setBrief(e.target.value)} placeholder="Describe the hook, product, pacing, visuals, and call to action…" aria-label="Video brief" />
      <div className="toolbar"><label className="control-label">Duration<select className="control" value={durationSec} onChange={e => setDurationSec(Number(e.target.value))}><option value="10">10 seconds</option><option value="15">15 seconds</option><option value="30">30 seconds</option><option value="60">60 seconds</option><option value="90">90 seconds</option></select>{voiceover && durationMode === 'voiceover' && <small className="muted">Soft target — narration can run a little over; if it runs far over, the voice speeds up slightly to pull it back</small>}</label><label className="control-label">Format<select className="control" value={style} onChange={e => setStyle(e.target.value)}>{STYLES.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</select></label><label className="control-label">Composer<select className="control" value={composer} onChange={e => setComposer(e.target.value)}><option value="template">Template · instant</option><option value="agent">AI composer</option></select></label></div>
      <AssetUpload onAssetsChange={updateAssets} assets={assets} />
      {composer === 'agent' && <><div className="provider-row"><label className="control-label">AI provider<select className="control" value={provider} onChange={e => { setProvider(e.target.value); setModel(''); }}><option value="openai-codex">OpenAI Codex</option><option value="opencode">OpenCode</option></select></label><label className="control-label">Model<select className="control" value={model} onChange={e => setModel(e.target.value)} disabled={modelsLoading || !models.length}>{modelsLoading ? <option>Loading models…</option> : models.length ? models.map(m => <option key={m.id} value={m.id}>{m.name}</option>) : <option>No models available</option>}</select></label></div>{provider === 'openai-codex' && !codexConnected && <div className="connection"><span><strong>Connect ChatGPT</strong><br /><span className="muted">Codex OAuth is required for AI composition.</span></span><button type="button" onClick={() => connectCodex('browser')}>Connect</button></div>}{provider === 'openai-codex' && login?.status === 'pending' && <div className="connection"><span>Waiting for OpenAI… {login.userCode && <><div className="login-code">{login.userCode}</div><small className="muted">Open {login.verificationUrl} to finish device login.</small></>}</span><button type="button" onClick={cancel}>Cancel</button></div>}{(connectError || modelsError) && <div className="error">{connectError || modelsError}</div>}</>}
      <div className="generation-options"><div className="toggle-row"><label className="toggle"><input type="checkbox" checked={music} onChange={e => setMusic(e.target.checked)} /> <span>Add music bed</span></label><label className="toggle"><input type="checkbox" checked={voiceover} onChange={e => setVoiceover(e.target.checked)} /> <span>Add voiceover</span></label>{voiceover && <label className="toggle" title="Duration becomes a soft target — the video follows the narration's natural length, and only speeds the voice up if it runs far past what you set."><input type="checkbox" checked={durationMode === 'voiceover'} onChange={e => setDurationMode(e.target.checked ? 'voiceover' : 'fixed')} /> <span>Let voiceover set duration</span></label>}</div>{voiceover && <div className="voice-grid"><label className="control-label">Voice provider<select className="control" value={voiceoverProvider} onChange={e => { const next = e.target.value; setVoiceoverProvider(next); setCustomVoiceId(false); if (VOICES[next]) setVoiceoverVoice(VOICES[next][0].value); }}>{Object.entries(VOICE_PROVIDERS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="control-label">Voice{voiceoverProvider === 'cartesia-tts' && <label className="custom-voice-toggle"><input type="checkbox" checked={customVoiceId} onChange={e => { const checked = e.target.checked; setCustomVoiceId(checked); if (checked) setVoiceoverVoice(''); else if (voiceOptions.length) setVoiceoverVoice(voiceOptions[0].value); }} /> Custom ID</label>}{customVoiceId ? <input className="control" value={voiceoverVoice} onChange={e => setVoiceoverVoice(e.target.value)} placeholder="Paste a Cartesia voice ID…" aria-label="Custom Cartesia voice ID" /> : <select className="control" value={voiceoverVoice} onChange={e => setVoiceoverVoice(e.target.value)} disabled={voiceoverProvider === 'cartesia-tts' && (cartesiaVoicesLoading || !voiceOptions.length)}>{voiceoverProvider === 'cartesia-tts' && cartesiaVoicesLoading ? <option>Loading voices…</option> : voiceOptions.length ? voiceOptions.map(v => <option key={v.value} value={v.value}>{v.label}</option>) : <option>No voices available</option>}</select>}{voiceoverProvider === 'cartesia-tts' && cartesiaVoicesError && <div className="error">{cartesiaVoicesError}</div>}</label><label className="control-label">Voice offset (s)<input type="number" step="0.1" min="-5" max="5" className="control" value={voiceoverOffsetSec} onChange={e => setVoiceoverOffsetSec(Number(e.target.value))} title="Negative = voice starts earlier. Positive = voice starts later. Fine-tune sync without regenerating the video." /></label></div>}</div><button className="primary generate-button" type="submit" disabled={loading || !brief.trim() || (composer === 'agent' && !model) || (voiceover && !voiceoverVoice.trim())}>{loading ? 'Preparing…' : 'Generate video ↗'}</button>
    </div>
  </form>;
}
